# Generated by Django 3.2.5 on 2021-11-23 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20211123_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_member',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_officer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_owner',
        ),
        migrations.CreateModel(
            name='UserClubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_pending', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_officer', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
