# Generated by Django 3.2.5 on 2021-11-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20211122_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
