# Generated by Django 3.2.5 on 2021-11-26 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20211124_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chess_xp',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
