# Generated by Django 3.2.5 on 2021-12-16 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20211127_2314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserClubs',
            new_name='Membership',
        ),
        migrations.AlterField(
            model_name='user',
            name='chess_xp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
