# Generated by Django 3.2.5 on 2021-11-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_remove_userclubs_application_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclubs',
            old_name='accepted',
            new_name='is_applicant',
        ),
    ]
